### ISSUE TITLE
The prices toggle does not work

### ISSUE THREAD

**Issue by Triquetra** [omardelarosa/obsidian-mtg#28]
While I have the toggle in the options UI to not include prices in the rendered table, turning it off does not seem to do anything. The prices still show up even with the option to show prices off.

**Comment by DonnieWest** [comment]
At least for me, the toggle is a bit oddly worded. It says "Show Prices" but the boolean in the code is "hide prices". So the toggle appears inverted. See the video here

https://github.com/omardelarosa/obsidian-mtg/assets/1453484/7c7af2b0-3f6c-405c-b2d7-76f48da482a1

**Comment by Triquetra** [comment]
Thanks, @DonnieWest. I think that's partially the issue. Toggling show prices on (which, as you said, is reversed), hides the prices. But, for me, the price column is still rendered, with a total of $0.00.
![2023-09-26 15_18_41-Blink and You're Dead 5DH - David - Obsidian v1 4 13](https://github.com/omardelarosa/obsidian-mtg/assets/195027/ebb70737-a2d1-4116-bea7-7e5efa55b723)

**Comment by omardelarosa** [comment]
Oh good catch on the toggle display text.  I had it as a "Show Prices" originally and defaulted to on, but I forgot to change the display text 🤦 .  I'll update this in the 1.0.8 version

**Comment by omardelarosa** [comment]
Okay I just published a new release 1.0.8.  @Triquetra can you update and see if the issue is corrected?

**Comment by Triquetra** [comment]
Yes, that clarifies the toggle meaning. Toggling "Hide Prices" on now hides the prices, and toggling it off shows the prices. 

The prices column is still there, however, and the $0.00 total is still shown at the bottom of the list. I don't know whether that is intended.

**Comment by omardelarosa** [comment]
Yeah looks like the hiding wasn't applied to the footers and a few other places.  Try updating to `1.0.9` and checking again.  From my end price hiding seems to be applied to totals as well now:

<img width="852" alt="Screenshot 2023-09-27 at 4 41 45 PM" src="https://github.com/omardelarosa/obsidian-mtg/assets/2551722/4cd2776d-b90e-420d-8fda-343f926a9200">

**Comment by Triquetra** [comment]
Success! Thanks, Omar.
